import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "../app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import clsx from "clsx";
import { Toaster } from "@/components/ui/toaster";
import NavBar from "@/components/navbar";
import { ScrollArea } from "@/components/ui/scroll-area";
import CustomScrollArea from "@/components/global/scrollbars";
import ModalProvider from "@/providers/modal-provider";
import dynamic from "next/dynamic";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={clsx("relative", jakarta.className)}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <ModalProvider>
              <CustomScrollArea>{children}</CustomScrollArea>
              <Toaster />
            </ModalProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
